---
title: "Job Aging Prospects Analysis"
author: "Dareen Padilla"
date: "2026-02-23"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(shiny)

# Reading Excel Files 
data_2013 <- read_excel("cps_2013_11b.xlsx")
data_2014 <- read_excel("cps_2014_11b.xlsx")
data_2015 <- read_excel("cps_2015_11b.xlsx")

knitr::opts_chunk$set(echo = TRUE)
```

```{r cleanup, echo = FALSE}

#Creating the cleanup function 
cleanup_data <- function(df, year) {
  df %>% 
    slice(-c(1:3)) %>%  #Removing The Headers 
    rename(
      occupation = 1, 
      `Total, 16 years and over` = 2, 
     `16_to_19 years` = 3, 
     `20_to_24 years` = 4, 
     `25_to_34_years` = 5,
     `35_to_44_years` = 6,
     `45_to_54_years` = 7,
     `55_to_64_years` = 8,
     `65_years_and_over` = 9, 
     `median_age` = 10
    ) %>% 
    filter(occupation != "Total employed") %>%  #Filtering out the Total Employed Row 
    
    #Removing median_age and Total 16yrs+ column before formatting table
    select(-c("Total, 16 years and over",median_age)) %>%
    
  #Changing the table from wide to long
    gather(
      key = "age_group", 
      value = "total_employment",
      -occupation
    ) %>% 
    mutate(
      year = year, 
      total_employment = (readr::parse_number(total_employment))
    )
}
``` 

```{r combining three years, echo = FALSE}

#Plugging the three year data into the cleanup function
cleaned_2013 <- cleanup_data(data_2013, 2013)
cleaned_2014 <- cleanup_data(data_2014, 2014)
cleaned_2015 <- cleanup_data(data_2015, 2015)


#Combining all three years into one table 
all_years <- bind_rows(
  cleaned_2013,
  cleaned_2014,
  cleaned_2015)
```

```{r Implementing Shiny Dropdowns, echo = FALSE}
selectInput("Select_AgeGroup", 
            "Select Age Group:", 
            choices = unique(all_years$age_group)
            )
selectInput("Select_Year", 
            "Select Year:", 
            choices = unique(all_years$year)
            )


renderTable({
  req(input$Select_AgeGroup, 
      input$Select_Year)
  
  all_years %>% 
    filter(age_group == input$Select_AgeGroup, 
           year== input$Select_Year) %>%
    
    slice_max(total_employment, n = 10) 
})
```

```{r Practicing Visualizations}
renderPlot({
  req(input$Select_AgeGroup, input$Select_Year)
  
  all_years %>% 
    filter(age_group == input$Select_AgeGroup,
           year == input$Select_Year) %>%
    slice_max(total_employment, n = 10) %>% 
    ggplot(aes(x = reorder(occupation, total_employment),     #Sorts the occupation based off of total employment
               y = total_employment, 
               fill = occupation)) +
    geom_col() + 
    labs(title = "Top 10 Ocupations based of Age Group & Year",
         x = "Occupation", 
         y = "Total Employment") +
    coord_flip() +
    theme_minimal() +
    theme(legend.position = "none")
})

```