---
title: "JobAgeProject"
author: "Obydah Jazaeri"
date: "2026-02-21"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library(shiny)
library(janitor)    
library(readxl)
library(dplyr)
library(tidyr)
library(stringr) 
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
data2017 <- read_excel("cpsaat11b.xlsx")
data2018 <- read_excel("data2018.xlsx")
data2019 <- read_excel("data2019.xlsx")
```

```{r cleaning}
clean_cps_year <- function(df, year) {
  
  df %>%
    slice(-c(1:3)) %>%   
    rename(
      occupation = 1,
      median_age = 2,
      `16_to_19_years` = 3,
      `20_to_24_years` = 4,
      `25_to_34_years` = 5,
      `35_to_44_years` = 6,
      `45_to_54_years` = 7,
      `55_to_64_years` = 8,
      `65_years_and_over` = 9
    ) %>%
    filter(occupation != "Total employed") %>%
    
    # DROP median age before pivoting
    select(-median_age) %>%
    
    pivot_longer(
      cols = -occupation,
      names_to = "age_group",
      values_to = "employment_thousands"
    ) %>%
    mutate(
      year = year,
      employment_thousands = readr::parse_number(employment_thousands)
    )
}

```

```{r create-cps-clean}
data2017_clean <- clean_cps_year(data2017, 2017)
data2018_clean <- clean_cps_year(data2018, 2018)
data2019_clean <- clean_cps_year(data2019, 2019)

cps_clean <- bind_rows(
  data2017_clean,
  data2018_clean,
  data2019_clean
)
```



```{r shiny graph }
ui <- fluidPage(
  
  titlePanel("Job Distribution by Occupation"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId = "year",
        label = "Select Year:",
        choices = sort(unique(cps_clean$year)),
        selected = max(cps_clean$year)
      ),
      
      selectInput(
        inputId = "occupation",
        label = "Select Occupations:",
        choices = sort(unique(cps_clean$occupation)),
        selected = unique(cps_clean$occupation)[1:6],
        multiple = TRUE
      )
    ),
    
    mainPanel(
      plotOutput("piePlot")
    )
  )
)

server <- function(input, output) {
  
  output$piePlot <- renderPlot({
    
    cps_clean %>%
      filter(
        year == input$year,
        occupation %in% input$occupation
      ) %>%
      group_by(occupation) %>%
      summarise(
        total_employment = sum(employment_thousands, na.rm = TRUE),
        .groups = "drop"
      ) %>%
      ggplot(aes(x = "", y = total_employment, fill = occupation)) +
      geom_col(width = 1) +
      coord_polar(theta = "y") +
      labs(
        title = paste("Job Distribution by Occupation,", input$year),
        fill = "Occupation"
      ) +
      theme_void()
  })
}
shinyApp(ui = ui, server = server)

```



